// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace RouletteGameApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220808143201_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Entities.Models.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("BetId");

                    b.Property<string>("BetOn")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BetValue")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("BetWinnings")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpinId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayoutId");

                    b.HasIndex("SpinId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("Entities.Models.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PayoutId");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("Entities.Models.Spin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("SpinId");

                    b.Property<long?>("SpinResult")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Spins");
                });

            modelBuilder.Entity("Entities.Models.Bet", b =>
                {
                    b.HasOne("Entities.Models.Payout", "Payout")
                        .WithMany("Bets")
                        .HasForeignKey("PayoutId");

                    b.HasOne("Entities.Models.Spin", "Spin")
                        .WithMany("Bets")
                        .HasForeignKey("SpinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payout");

                    b.Navigation("Spin");
                });

            modelBuilder.Entity("Entities.Models.Payout", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("Entities.Models.Spin", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
