// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace RouletteGameApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Entities.Models.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("BetId");

                    b.Property<string>("BetOn")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BetValue")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("BetWinnings")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpinId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayoutId");

                    b.HasIndex("SpinId");

                    b.ToTable("Bets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            BetOn = "HIGH",
                            BetValue = 50.62m,
                            BetWinnings = 560.20m,
                            PayoutId = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            SpinId = new Guid("c8d4c053-49b6-410c-bc78-2d54a9891870"),
                            TimestampUtc = new DateTime(2022, 8, 8, 14, 35, 34, 390, DateTimeKind.Utc).AddTicks(1354)
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            BetOn = "RED",
                            BetValue = 46.45m,
                            BetWinnings = 384.78m,
                            PayoutId = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            SpinId = new Guid("4d490a70-94ce-4d15-9494-5248280c2ce3"),
                            TimestampUtc = new DateTime(2022, 8, 8, 14, 35, 34, 390, DateTimeKind.Utc).AddTicks(1358)
                        });
                });

            modelBuilder.Entity("Entities.Models.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PayoutId");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Payouts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            TimestampUtc = new DateTime(2022, 8, 8, 14, 35, 34, 390, DateTimeKind.Utc).AddTicks(1291)
                        },
                        new
                        {
                            Id = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            TimestampUtc = new DateTime(2022, 8, 8, 14, 35, 34, 390, DateTimeKind.Utc).AddTicks(1293)
                        });
                });

            modelBuilder.Entity("Entities.Models.Spin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("SpinId");

                    b.Property<long?>("SpinResult")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Spins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8d4c053-49b6-410c-bc78-2d54a9891870"),
                            SpinResult = 5L,
                            TimestampUtc = new DateTime(2022, 8, 8, 14, 35, 34, 390, DateTimeKind.Utc).AddTicks(1137)
                        },
                        new
                        {
                            Id = new Guid("4d490a70-94ce-4d15-9494-5248280c2ce3"),
                            SpinResult = 5L,
                            TimestampUtc = new DateTime(2022, 8, 8, 14, 35, 34, 390, DateTimeKind.Utc).AddTicks(1140)
                        });
                });

            modelBuilder.Entity("Entities.Models.Bet", b =>
                {
                    b.HasOne("Entities.Models.Payout", "Payout")
                        .WithMany("Bets")
                        .HasForeignKey("PayoutId");

                    b.HasOne("Entities.Models.Spin", "Spin")
                        .WithMany("Bets")
                        .HasForeignKey("SpinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payout");

                    b.Navigation("Spin");
                });

            modelBuilder.Entity("Entities.Models.Payout", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("Entities.Models.Spin", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
